# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone',
            new_name='photo',
        ),
    ]
