# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20171212_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 13, 9, 59, 202773, tzinfo=utc)),
        ),
    ]
