# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171212_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 8, 51, 26, 948156, tzinfo=utc)),
        ),
    ]
