# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20171217_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 8, 55, 44, 248873, tzinfo=utc)),
        ),
    ]
