# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlgoArticls',
            new_name='BlogArticls',
        ),
    ]
